Task: Add CI/CD
DariaAres/trainee-planner pull request #11
Opened 2023-08-08 22:02 UTC by DariaAres

## Task: 
Add CI/CD using github actions
## Change proposed in this pull request:
* A workflow using github actions was configured
* Job for CI was writed:
   - сhecking the code style according to rubocop
   - verification of all performance tests
   - simplecov/codecov to check application and method test coverage

2023-08-09 09:24 UTC, Iorhael submitted a review, later dismissed

2023-08-09 16:24 UTC, TsikhanauDzmitry commented on .github/workflows/rubyonrails.yml
Сделай пожалуйста так, чтобы отображалось 3 проверки на гитхабе:

1. Rubocop
2. RSpec
3. code-coverage

2023-08-10 01:04 UTC, DariaAres commented on .github/workflows/rubyonrails.yml
сделала

2023-08-10 08:51 UTC, Iorhael submitted a review, later dismissed

2023-08-10 08:56 UTC, TsikhanauDzmitry requested changes

2023-08-10 08:56 UTC, TsikhanauDzmitry commented on coverage/.last_run.json
Не уверен, что данная папка должна храниться на гитхабе

2023-08-10 09:11 UTC, DariaAres commented on coverage/.last_run.json
закинула в гитигнор

2023-08-10 09:14 UTC, Iorhael approved these changes

2023-08-11 07:20 UTC, TsikhanauDzmitry approved these changes

2023-08-11 07:54 UTC, merged