Task: Write readme file
DariaAres/trainee-planner pull request #13
Opened 2023-08-10 04:08 UTC by DariaAres

## Task: 
In README.md add instructions for running dockerized app and on the local host 
## Change proposed in this pull request:
Instructions were wrote in READMY.md:
- Overview
- Installation
- Local running
- Run in docker

2023-08-11 08:17 UTC, Iorhael submitted a review, later dismissed

2023-08-11 08:37 UTC, Iorhael approved these changes

2023-08-11 10:43 UTC, TsikhanauDzmitry requested changes

2023-08-11 10:43 UTC, TsikhanauDzmitry commented on README.md
А как запускать тесты у данного приложения?

2023-08-14 08:13 UTC, Iorhael approved these changes

2023-08-14 11:11 UTC, TsikhanauDzmitry approved these changes

2023-08-19 20:09 UTC, merged