Task: Add user model
DariaAres/trainee-planner pull request #15
Opened 2023-08-11 21:40 UTC by DariaAres

2023-08-21 17:02 UTC, DariaAres commented on db/migrate/20230811214111_devise_create_users.rb
> +      # t.datetime :locked_at
убрала

2023-08-21 17:03 UTC, DariaAres commented on db/migrate/20230811214111_devise_create_users.rb
> +    # add_index :users, :unlock_token,         unique: true
убрала

2023-08-21 17:04 UTC, DariaAres commented on db/seeds/users_seeds.rb
> +    password: Faker::Internet.password
поставила у всех пароль '123456', а остальные данные буду если что по бд смотреть

2023-08-21 18:06 UTC, DariaAres commented on spec/support/database_cleaner.rb
> +  end
Этот блок грубо-говоря гласит что пока наш Capybara.current_driver не на тестовом окружениимы очищаем базу данных используя стратегию :truncation которая, полностью очищая таблицы без удаления самой структуры таблицы или удаления записей по отдельности и блокирует всю таблицу, что предотвращает выполнение других транзакций, пока выполняется усечение

2023-08-22 07:04 UTC, TsikhanauDzmitry requested changes

2023-08-22 07:04 UTC, TsikhanauDzmitry commented on db/migrate/20230811214111_devise_create_users.rb
> +      t.string :last_name, default: ' '
В БД хранится пробел?

2023-08-22 07:04 UTC, TsikhanauDzmitry commented on db/seeds/users_seeds.rb
> +    email: Faker::Internet.email,
Не рекомендую давать рандомные email'ы. Лучше делать номерные: `user_#{i}@example.com`

2023-08-22 07:04 UTC, TsikhanauDzmitry commented on db/seeds/users_seeds.rb
> +    password: '123456'
Предложение: сделать пароль `password`. Заметил, что на проектах в основном делают так, если нет требований к паролю

2023-08-22 07:04 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    email { Faker::Internet.email }
Я бы добавил, что email у нас уникальный. Как считаешь?

2023-08-23 05:03 UTC, DariaAres commented on db/migrate/20230811214111_devise_create_users.rb
> +      t.string :last_name, default: ' '
Исправила на пустую строку

2023-08-23 05:03 UTC, DariaAres commented on db/seeds/users_seeds.rb
> +    email: Faker::Internet.email,
Переделала

2023-08-23 05:03 UTC, DariaAres commented on db/seeds/users_seeds.rb
> +    password: '123456'
Переделала

2023-08-23 05:04 UTC, DariaAres commented on spec/factories/users.rb
> +    email { Faker::Internet.email }
И правда.. Переделала

2023-08-23 05:35 UTC, DariaAres commented on app/javascript/application.js
> -import * as bootstrap from "bootstrap"
Нечаянно, исправила

2023-08-23 05:47 UTC, DariaAres commented on .github/actions/build/action.yml
Создала для этих изменений [pr](https://github.com/DariaAres/trainee-planner/pull/19)

2023-08-23 05:49 UTC, DariaAres commented on .github/workflows/rubyonrails.yml
Перенесла изменения в пр [pr](https://github.com/DariaAres/trainee-planner/pull/19)

2023-08-23 06:07 UTC, DariaAres commented on Gemfile
> -
Так как стратегии database_cleaner-a на ative-record не соответствуют стратениям на redis orm и при запуске тестов все время выдет ошибку "DatabaseCleaner::UnknownStrategySpecified: The 'truncation' strategy does not exist for the redis ORM!"

2023-08-23 06:24 UTC, DariaAres commented on config/routes.rb
> +  devise_for :users
По сравнению с контроллерами и видом меньшее, так что, убрала

2023-08-23 06:48 UTC, DariaAres commented on config/database.yml
> +  port: 8888
Исправила. Так как эти изменения относятся к коммиту измеенения ci/cd, они перенесены в pr https://github.com/DariaAres/trainee-planner/pull/19

2023-08-24 11:18 UTC, Iorhael approved these changes

2023-08-24 12:30 UTC, TsikhanauDzmitry requested changes

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on app/models/user.rb
> +  validates :password, presence: true, length: { within: 6..20}
После `20` забыла пробел)

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on db/seeds.rb
> +load('./db/seeds/users_seeds.rb') if Rails.env.development?
Не рекомендую отделять сиды файлами с разными моделями, потому что потом могут быть проблемы с ассоциациями и тп

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on db/seeds/users_seeds.rb
> +    email: 'user_#{i}@example.com',
Что такое `i` в данной реализации? Я лично вижу только `_index`

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
Фамилия - необязательное поле. Может было бы лучше сделать для него отдельный trait? Что думаешь?

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +    end
Странный тест, потому что у тебя четкая валидация есть:
```
validates :password, presence: true
```

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +  describe 'Default value' do
Задумка данных тестов интересная, но с точки зреня будущих исправлений и изменений, думаю, что от них придется отказаться

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +    end
Не обязательно выделять данные тесты с помощью `describe`/`context`. Достаточно просто `it` блоков

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +      context '\'@\' is not presence' do
Есть четки требования названий `describe`/`context`/`it` блоков. Почитай и исправь свои, пожалуйста

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +      let(:user) { build(:user, email: 'example@gmail.com') }
Я бы не рекомендовал оставлять реальные домены электронных писем

2023-08-24 12:30 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +    end
Насколько я знаю, есть специальные тесты от rspec, которые могут сами проверять длину строк

2023-08-25 05:42 UTC, DariaAres commented on Gemfile
> +  gem 'undercover'
Убрала. Я просто подумала, что раз они в методичке то их надо бы добавить. Но если что потом отдельным пиаром сделаю может, если они конечно нужны

2023-08-25 05:42 UTC, DariaAres commented on app/models/user.rb
> +  validates :password, presence: true, length: { within: 6..20}
исправила

2023-08-25 05:42 UTC, DariaAres commented on db/migrate/20230811214111_devise_create_users.rb
> +      t.string :first_name, null: false, default: ''
убрала

2023-08-25 05:42 UTC, DariaAres commented on db/seeds.rb
> +load('./db/seeds/users_seeds.rb') if Rails.env.development?
исправила

2023-08-25 05:43 UTC, DariaAres commented on db/seeds/users_seeds.rb
> +    email: 'user_#{i}@example.com',
исправила

2023-08-25 05:43 UTC, DariaAres commented on spec/models/user_spec.rb
> +  describe 'Default value' do
убрала

2023-08-25 05:43 UTC, DariaAres commented on spec/models/user_spec.rb
> +    end
исправила

2023-08-25 05:43 UTC, DariaAres commented on spec/models/user_spec.rb
> +      context '\'@\' is not presence' do
исправила

2023-08-25 05:43 UTC, DariaAres commented on spec/models/user_spec.rb
> +      let(:user) { build(:user, email: 'example@gmail.com') }
исправила

2023-08-25 05:43 UTC, DariaAres commented on spec/models/user_spec.rb
> +    end
исправила

2023-08-25 05:51 UTC, DariaAres commented on spec/factories/users.rb
> +    last_name { Faker::Name.last_name }
Может, сделала trait для фамилии

2023-08-25 06:29 UTC, DariaAres commented on spec/models/user_spec.rb
> +    end
Да, действительно странный. Помоему это связано с тем что `described_class.new` создает `#<User id: nil, email: "", first_name: nil, last_name: nil, created_at: nil, updated_at: nil>` (я в этом примере уже убрала default на имя и фам.), хотя в схеме указанно, что first_name, created_at, updated_at являются null: false. Наверно с паролем сработало аналогично. Интересно почему метод new так работает:
![Screenshot from 2023-08-25 09-21-17](https://github.com/DariaAres/trainee-planner/assets/120682364/193047c0-fc26-4c01-ad21-30ce883b11ed)
Хотя метод `create` действует иначе
![Screenshot from 2023-08-25 09-24-34](https://github.com/DariaAres/trainee-planner/assets/120682364/43e08bac-00d9-4519-b0ba-1b6ad9530acc
И даже при использовании `described_class.create` создается объект `#<User id: nil, email: "", first_name: nil, last_name: nil, created_at: nil, updated_at: nil>`

2023-08-25 09:12 UTC, Iorhael commented on db/seeds.rb
Сделай, пожалуйста, сиды только для development окружения.

2023-08-28 09:06 UTC, TsikhanauDzmitry requested changes

2023-08-28 09:06 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +  User.create_or_find_by!(
А по какому полю ищется пользователь? Если запустить Сиды еще раз, то все пройдет без ошибок?

2023-08-28 09:06 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    trait :last_name do
Я бы рекомендовал делать трейды с более точными именами. В нашем случае было бы славно сделать что-то типа: `with_last_name`

2023-08-28 09:06 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +      last_name { 'last_name' }
Почему не используется Faker?

2023-08-28 09:06 UTC, TsikhanauDzmitry commented on spec/rails_helper.rb
> +Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
Было бы славно отделить это пустыми строчками от комментариев

2023-08-28 09:06 UTC, TsikhanauDzmitry commented on spec/models/user_spec.rb
> +    end
Название не состыкуется с тестом. Почему так?

2023-08-29 05:40 UTC, DariaAres commented on db/seeds/development.rb
> +  User.create_or_find_by!(
Пользователь ищется по сгеренерированным полям имени, фамили, полям почты  и пароля. Если запустить сиды еще раз то все пройдет без ошибок, так как метод не создаст уже существующих пользователей

2023-08-29 05:45 UTC, DariaAres commented on spec/factories/users.rb
> +      last_name { 'last_name' }
Исправила

2023-08-29 05:45 UTC, DariaAres commented on spec/rails_helper.rb
> +Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }
Отделила

2023-08-29 05:46 UTC, DariaAres commented on spec/models/user_spec.rb
> +    end
У меня нет оправданий. Исправила

2023-08-29 05:47 UTC, DariaAres commented on spec/factories/users.rb
> +    trait :last_name do
Переделала

2023-08-29 05:47 UTC, DariaAres commented on db/seeds.rb
Сделала

2023-08-29 07:59 UTC, Iorhael approved these changes

2023-08-29 08:52 UTC, TsikhanauDzmitry requested changes

2023-08-29 08:52 UTC, TsikhanauDzmitry commented on db/seeds/development.rb
> +  User.create_or_find_by!(
А как оно может искать по паролю?.. Может было бы достаточно искать только по почте, раз это уникальное поле?

2023-08-29 08:52 UTC, TsikhanauDzmitry commented on spec/factories/users.rb
> +    password { Faker::Internet.password }
У тебя есть строгие ограничения на длину пароля. Ты уверена, что данный пароль будет всегда соответствовать условиям?

2023-08-30 05:32 UTC, DariaAres commented on db/seeds/development.rb
> +  User.create_or_find_by!(
Переделала

2023-08-30 05:33 UTC, DariaAres commented on spec/factories/users.rb
> +    password { Faker::Internet.password }
Добавила дополнителные параметры

2023-08-30 08:38 UTC, Iorhael approved these changes

2023-08-30 08:43 UTC, TsikhanauDzmitry approved these changes

2023-09-06 20:04 UTC, merged