Task: Adapt ci/cd to run rspec tests
DariaAres/trainee-planner pull request #19
Opened 2023-08-23 05:45 UTC by DariaAres

## Task:
 Adapt ci/cd to run rspec tests
## Changes proposed in this pull request:

2023-08-23 08:05 UTC, Iorhael approved these changes

2023-08-24 12:17 UTC, TsikhanauDzmitry requested changes

2023-08-24 12:17 UTC, TsikhanauDzmitry commented on .env
Данный файл обычно не хранится на удаленных репозиториях. А как пример есть файл `.env.example`

2023-08-25 20:00 UTC, Iorhael approved these changes

2023-08-28 09:14 UTC, TsikhanauDzmitry requested changes

2023-08-28 09:14 UTC, TsikhanauDzmitry commented on .env
Этот файл должен быть в `.gitignore`

2023-08-28 09:14 UTC, TsikhanauDzmitry commented on .env.example
> +MYSQL_HOST=localhost
Обычно тут не хранятся данные. Тип просто достаточно:

```
MYSQL_ROOT_PASSWORD=
MYSQL_ROOT_USER=
```

2023-08-29 06:57 UTC, DariaAres commented on .env
Сделано

2023-08-29 06:57 UTC, DariaAres commented on .env.example
> +MYSQL_HOST=localhost
Испрвила

2023-08-29 08:01 UTC, Iorhael submitted a review, later dismissed

2023-08-29 08:06 UTC, DariaAres commented on .env
Исправила

2023-08-29 08:52 UTC, TsikhanauDzmitry submitted a review, later dismissed

2023-08-30 05:57 UTC, merged