Task: Add main view and controller for home page
DariaAres/trainee-planner pull request #20
Opened 2023-08-30 06:14 UTC by DariaAres

2023-09-01 11:02 UTC, DariaAres commented on app/views/layouts/application.html.erb
> +  <% end %>
Вынесла

2023-09-01 11:03 UTC, DariaAres commented on app/helpers/main_helper.rb
Удалила

2023-09-01 11:33 UTC, Iorhael approved these changes

2023-09-01 12:19 UTC, TsikhanauDzmitry requested changes

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/views/layouts/_alert.html.erb
1. А вдруг у нас не только `alert` и `notice` будут?
2. Не думаю, что это соответствует принципу DRY. Как считаешь?

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +        </div>
Я бы рекомендовал это вынести в отдельный partial.

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +  <a class="navbar-brand home-link" href="/">Trainee Planner</a>
Для ссылок используй хэлпер-метод `link_to`

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/views/layouts/_header.html.erb
> +  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navig
Что делает данная кнопка?

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/views/layouts/application.html.erb
> +  <%= render partial: 'layouts/alert' %>
https://guides.rubyonrails.org/layouts_and_rendering.html#partial-layouts

Советую почитать

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/views/main/home.html.erb
> +  <h4 class="text-shadow"><font color="#2B5035"><%= t('hi')%>!</font></h4>
Очень вольное название `hi`

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/views/main/home.html.erb
> +  <h4 class="text-shadow"><font color="#2B5035"><%= t('hi')%>!</font></h4>
Никаких `<font color="#2B5035">`! Лучше сделать отдельный css-класс, чем указывать стили прямо в файлах

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on app/controllers/main_controller.rb
> +  def home; end
По идее это index метод.

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on config/routes.rb
> +  root "main#home"
Зачем и get, и root?

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on spec/views/main/home.html.erb_spec.rb
> +  end
Это можно в одну строку написать.

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on spec/views/main/home.html.erb_spec.rb
Я бы сюда добавил тесты хэдера и футера. (в отдельные файлы)

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on spec/routes/main_routes_spec.rb
> +    expect(get: '/main/home').to route_to('main#home')
Обычно `root == '/'`. Почему тут иначе?

2023-09-01 12:19 UTC, TsikhanauDzmitry commented on spec/requests/main_spec.rb
Тесты на реквест мы не пишем. Добавь это в тесты на контроллер

2023-09-02 06:30 UTC, DariaAres commented on app/controllers/main_controller.rb
> +class MainController < ApplicationController
Изменила

2023-09-04 07:02 UTC, DariaAres commented on app/assets/stylesheets/styles.css
> +h4,
убрала лишнее

2023-09-04 07:02 UTC, DariaAres commented on app/assets/stylesheets/styles.css
> +}
убрала лишнее

2023-09-04 07:02 UTC, DariaAres commented on app/assets/stylesheets/styles.css
> +}
исправила

2023-09-04 07:02 UTC, DariaAres commented on app/assets/stylesheets/styles.css
> +}
исправила

2023-09-04 08:37 UTC, DariaAres commented on app/views/layouts/_alert.html.erb
изменила файл на notification

2023-09-04 08:53 UTC, DariaAres commented on app/views/layouts/_header.html.erb
> +        </div>
Вынесла

2023-09-04 08:53 UTC, DariaAres commented on app/controllers/main_controller.rb
> +  def home; end
Исправила

2023-09-05 06:07 UTC, DariaAres commented on app/views/layouts/_header.html.erb
> +  <a class="navbar-brand home-link" href="/">Trainee Planner</a>
исправила

2023-09-05 06:08 UTC, DariaAres commented on app/views/layouts/_header.html.erb
> +  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navig
Ничего) Убрала

2023-09-05 07:05 UTC, DariaAres commented on spec/routes/main_routes_spec.rb
> +    expect(get: '/main/home').to route_to('main#home')
исправила

2023-09-05 07:05 UTC, DariaAres commented on spec/requests/main_spec.rb
исправила

2023-09-05 07:59 UTC, DariaAres commented on spec/views/main/home.html.erb_spec.rb
> +  end
изменила

2023-09-05 18:22 UTC, DariaAres commented on config/routes.rb
> +  root "main#home"
исправила

2023-09-05 18:22 UTC, DariaAres commented on app/views/main/home.html.erb
> +  <h4 class="text-shadow"><font color="#2B5035"><%= t('hi')%>!</font></h4>
исправила

2023-09-05 18:22 UTC, DariaAres commented on app/views/main/home.html.erb
> +  <h4 class="text-shadow"><font color="#2B5035"><%= t('hi')%>!</font></h4>
исправила

2023-09-05 18:23 UTC, DariaAres commented on spec/views/main/home.html.erb_spec.rb
добавила

2023-09-06 10:24 UTC, Iorhael commented on app/views/layouts/_dropdown.html.erb
> +    <li><%= link_to "English", "/en", class: "dropdown-item"%></li>
Я думаю, что следует добавить пробелы после `class: "dropdown-item"`

2023-09-06 10:24 UTC, Iorhael commented on app/views/layouts/_dropdown.html.erb
Мне кажется, что название не очень хорошо описывает, для чего это partial. Может выбрать что-нибудь вроде `_locale.html.erb`

2023-09-06 10:24 UTC, Iorhael commented on app/views/layouts/_notifications.html.erb
Мне кажется, что Дмитрий имел в виду, что следуют сделать общую форму для всех flash messages

2023-09-06 11:58 UTC, DariaAres commented on app/views/layouts/_dropdown.html.erb
> +    <li><%= link_to "English", "/en", class: "dropdown-item"%></li>
добавила

2023-09-06 11:58 UTC, DariaAres commented on app/views/layouts/_dropdown.html.erb
изменила

2023-09-06 11:59 UTC, DariaAres commented on app/views/layouts/_notifications.html.erb
изменила

2023-09-06 17:14 UTC, Iorhael submitted a review, later dismissed

2023-09-07 13:04 UTC, TsikhanauDzmitry requested changes

2023-09-07 13:04 UTC, TsikhanauDzmitry commented on spec/features/home_features_spec.rb
> +    end
Это нужно в одну строчку через `{ }` писать. Не нужно писать блоки в одну строчку через `do - end` блоки

2023-09-07 13:04 UTC, TsikhanauDzmitry commented on spec/features/home_features_spec.rb
> +    end
Давай для этого мы сделаем отдельный файл, где будут тестироваться только смены языков. Все-таки у тебя для этого даже логика немного другая

2023-09-07 13:04 UTC, TsikhanauDzmitry commented on spec/support/routes/home_routes_spec.rb
Почему папка `support`?

2023-09-07 13:04 UTC, TsikhanauDzmitry commented on spec/views/home/index.html.erb_spec.rb
> +    end
Такого в view тестах быть не должно

2023-09-11 14:06 UTC, DariaAres commented on spec/views/home/index.html.erb_spec.rb
> +    end
убрала

2023-09-11 14:06 UTC, DariaAres commented on spec/support/routes/home_routes_spec.rb
переместила

2023-09-11 14:06 UTC, DariaAres commented on spec/features/home_features_spec.rb
> +    end
сделала

2023-09-11 14:06 UTC, DariaAres commented on spec/features/home_features_spec.rb
> +    end
исправила

2023-09-11 14:06 UTC, DariaAres commented on app/views/layouts/_header.html.erb
исправила

2023-09-11 14:06 UTC, DariaAres commented on app/views/layouts/_footer.html.erb
> +<h6 class="p-3">© 2023 Copyright</h6>
исправила

2023-09-11 14:07 UTC, DariaAres commented on app/views/layouts/_flash_messages.html.erb
> +    <%= fash[type] %>
опечатка, исправила

2023-09-11 14:12 UTC, Iorhael commented on app/helpers/application_helper.rb
> +  end
Лучше будет создать отдельный хелпер для этих целей и сделать переменную `styles` отдельной константой и зафризить.

2023-09-11 14:44 UTC, DariaAres commented on app/helpers/application_helper.rb
> +  end
сделала

2023-09-12 06:18 UTC, TsikhanauDzmitry approved these changes

2023-09-12 06:20 UTC, merged