Task: Add controller and view for categories
DariaAres/trainee-planner pull request #21
Opened 2023-09-05 18:41 UTC by DariaAres

2023-09-15 20:28 UTC, Iorhael commented on app/views/layouts/_header.html.erb
> +      <%= link_to t('category.categories'), "/categories", class: "btn btn-secondary" %>
Мне кажется, что лучше было бы воспользоваться path helper-ом вместо `/categories`

2023-09-15 20:28 UTC, Iorhael commented on config/routes.rb
> +  root 'categories#index'
А почему рутовый роут не `home#index`?

2023-09-15 20:28 UTC, Iorhael commented on config/routes.rb
> +  get '/categories/:id', to: 'categories#edit'
Не очень понимаю, для чего были добавлены эти роуты, если прописан `resource:`

2023-09-16 05:46 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +      flash[:success] = 'Category Has Been successfully Created'
добавила

2023-09-16 09:14 UTC, DariaAres commented on config/routes.rb
> +  get '/categories/:id', to: 'categories#edit'
Убрала роут к индексу, а остальные переопределены от resource: . Если оставить чисто ресурсы у new будет запрашивать id, а categories/:id будут ссылаться на show, а не edit

2023-09-16 09:14 UTC, DariaAres commented on config/routes.rb
> +  root 'categories#index'
ну, пока тут нет домашней страницы. Потом уберется при резолве конфликтов, если так можно конечно : /

2023-09-16 09:14 UTC, DariaAres commented on app/views/layouts/_header.html.erb
> +      <%= link_to t('category.categories'), "/categories", class: "btn btn-secondary" %>
исправила

2023-09-16 09:14 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +    @category = Category.find(params[:id])
сделала

2023-09-16 09:14 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +      flash[:success] = 'Category Has Been successfully Created'
добавила

2023-09-16 10:05 UTC, DariaAres commented on config/routes.rb
> +  root 'categories#index'
в общем исправила

2023-09-18 08:12 UTC, Iorhael submitted a review, later dismissed

2023-10-11 11:00 UTC, Iorhael commented on spec/controllers/categories/new_spec.rb
> +        expect(flash[:notice]).to eq('Category has been successfully created')
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:01 UTC, Iorhael commented on spec/features/categories/create_spec.rb
> +    it { expect(page).to have_content('Category has been successfully created') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:01 UTC, Iorhael commented on spec/features/categories/create_spec.rb
> +    it { expect(page).to have_content('Name has already been taken') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:01 UTC, Iorhael commented on spec/features/categories/delete_spec.rb
> +      it { expect(page).to have_content('Category has been deleted successfully') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:02 UTC, Iorhael commented on spec/features/categories/delete_spec.rb
> +      it { expect(page).to have_no_content('Delete') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:02 UTC, Iorhael commented on spec/features/categories/edit_spec.rb
> +      it { expect(page).to have_content('Category has been updated successfully') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:02 UTC, Iorhael commented on spec/features/categories/edit_spec.rb
> +      it { expect(page).to have_content('Name can\'t be blank') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:02 UTC, Iorhael commented on spec/features/categories/edit_spec.rb
> +      it { expect(page).to have_no_content('Category has been updated successfully') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:02 UTC, Iorhael commented on spec/features/categories/index_spec.rb
> +      it { expect(page).to have_content('Categories') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:02 UTC, Iorhael commented on spec/features/categories/index_spec.rb
> +      it { expect(page).to have_button('Delete') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:03 UTC, Iorhael commented on spec/features/categories/index_spec.rb
> +      it { expect(page).to have_no_content('Create new') }
Проверь, пожалуйста, сообщение с использованием `I18n`

2023-10-11 11:05 UTC, Iorhael commented on spec/routings/categories_routing_spec.rb
Добавь, пожалуйста, тесты на put/putch и post запросы

2023-10-11 11:35 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +    redirect_to categories_path, status: :see_other, notice: t('category.category_deleted')
Добавила

2023-10-11 11:37 UTC, DariaAres commented on config/routes.rb
> +    get '/categories/:id', to: 'categories#edit'
Ты уже подобным вопросом интересовался https://github.com/DariaAres/trainee-planner/pull/21#discussion_r1327936590

2023-10-12 05:37 UTC, DariaAres commented on spec/controllers/categories/delete_spec.rb
> +        expect(flash[:notice]).to match('Category has been deleted successfully')
исправила

2023-10-12 05:38 UTC, DariaAres commented on spec/controllers/categories/new_spec.rb
> +        expect(flash[:notice]).to eq('Category has been successfully created')
исправила

2023-10-12 05:39 UTC, DariaAres commented on spec/features/categories/create_spec.rb
> +    it { expect(page).to have_content('Category has been successfully created') }
исправила

2023-10-12 05:41 UTC, DariaAres commented on spec/features/categories/create_spec.rb
> +    it { expect(page).to have_content('Name has already been taken') }
исправила

2023-10-12 05:42 UTC, DariaAres commented on spec/features/categories/delete_spec.rb
> +      it { expect(page).to have_content('Category has been deleted successfully') }
испрвила

2023-10-12 05:42 UTC, DariaAres commented on spec/features/categories/delete_spec.rb
> +      it { expect(page).to have_no_content('Delete') }
исправила

2023-10-12 05:54 UTC, DariaAres commented on spec/features/categories/edit_spec.rb
> +      it { expect(page).to have_content('Name can\'t be blank') }
исправила

2023-10-12 05:54 UTC, DariaAres commented on spec/features/categories/edit_spec.rb
> +      it { expect(page).to have_no_content('Category has been updated successfully') }
исправила

2023-10-12 05:55 UTC, DariaAres commented on spec/features/categories/index_spec.rb
> +      it { expect(page).to have_content('Categories') }
исправила

2023-10-12 05:55 UTC, DariaAres commented on spec/features/categories/index_spec.rb
> +      it { expect(page).to have_button('Delete') }
исправила

2023-10-12 05:55 UTC, DariaAres commented on spec/features/categories/index_spec.rb
> +      it { expect(page).to have_no_content('Create new') }
исправила

2023-10-12 06:08 UTC, DariaAres commented on spec/routings/categories_routing_spec.rb
У меня там уже есть тест на `edit`, но ты прав добавила на тест на `delete` и `create`

2023-10-12 10:42 UTC, TsikhanauDzmitry requested changes
Тесты проверю после исправления логики и других комментариев

2023-10-12 10:42 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @categories = current_user.categories.all
Где пагинация?

2023-10-12 10:42 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @category = current_user.categories.create(category_params)
Как известно: операция `create = new -> save`. Думаю, что тут правильно было бы сделать `new`

2023-10-12 10:42 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +      render :new, status: :unprocessable_entity
А сообщения по ошибкам выводятся?

2023-10-12 10:42 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +
Зачем тут пустая строчка?)

2023-10-12 10:42 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +
Тут зачем пустая строчка?..

2023-10-12 10:42 UTC, TsikhanauDzmitry commented on app/models/category.rb
> +  has_many :user_categories
А почему убрала `dependent: :destroy`?

2023-10-13 06:21 UTC, DariaAres commented on spec/features/categories/index_spec.rb
> +      it { expect(page).to have_button('Delete') }
Исправила

2023-10-13 06:21 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +    @categories = current_user.categories.all
Добавила

2023-10-13 07:44 UTC, DariaAres commented on app/models/category.rb
> +  has_many :user_categories
Так как, когда я удаляю категорию, `depent: :destroy` удаляет привязанный к ней кортеж UserCategories, но в его модели также стоял `depent: :destroy` как на юзере так и на категории. В удаляемом кортеже этим юзером по логике является текущий пользователь, а категория уже удалена, и из-за этого как я думаю возникала ошибка. Поэтому я просто убрала `depent: :destroy` на соединительную таблицу категорий с пользователем. Но сейчас мне кажется это не разумно, поэтому я убрала в модели UserCategories все `depent: :destroy`, в категориях вернула чтобы удалялась связь между юзером и категорией и на события в категории добавила `depent: :delete_all` чтобы при удалении категории удалялись все события, привязанные к ней

2023-10-13 13:23 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +
убрала

2023-10-13 13:23 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +
убрала

2023-10-13 13:23 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +      render :new, status: :unprocessable_entity
добавила

2023-10-16 09:28 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +    @category = current_user.categories.create(category_params)
Оставила `create`, но вместо метода `save` написала проверку на то сохранилась ли создаваемая категория в базу

2023-10-23 07:07 UTC, TsikhanauDzmitry requested changes

2023-10-23 07:07 UTC, TsikhanauDzmitry commented on app/controllers/categories_controller.rb
> +    @categories = current_user.categories.all.page(params[:page]).per(params[:per_page]).order('name')
Разве обязательно передавать строкой `'name'`? Не лучше ли использовать символы?

2023-10-23 07:07 UTC, TsikhanauDzmitry commented on app/views/categories/index.html.erb
> +  </div>
Думаю, что для этого можно создать отдельный `partial`

2023-10-23 07:07 UTC, TsikhanauDzmitry commented on app/views/categories/index.html.erb
> +            <th width="450px">
Мы же договорились, что все указываем в css-классах

2023-10-24 05:33 UTC, DariaAres commented on app/controllers/categories_controller.rb
> +    @categories = current_user.categories.all.page(params[:page]).per(params[:per_page]).order('name')
исправила

2023-10-24 05:37 UTC, DariaAres commented on app/views/categories/index.html.erb
> +  </div>
Исправила

2023-10-24 05:39 UTC, DariaAres commented on app/views/categories/index.html.erb
> +            <th width="450px">
исправила

2023-10-25 13:32 UTC, TsikhanauDzmitry approved these changes

2023-10-25 13:32 UTC, TsikhanauDzmitry commented on app/assets/stylesheets/styles/table.css
А зачем тут пустой файл?

2023-10-27 09:55 UTC, merged