Task: Add gem kaminari
DariaAres/trainee-planner pull request #24
Opened 2023-09-13 08:54 UTC by DariaAres

## Task:
Add gem kaminari

## Changes proposed in this pull request:
Added 'gem kaminari' to develop and test env in Gemfile and installed

2023-09-13 17:17 UTC, Iorhael approved these changes

2023-09-15 09:49 UTC, TsikhanauDzmitry requested changes

2023-09-15 09:49 UTC, TsikhanauDzmitry commented on Gemfile
> +  gem 'kaminari'
У тебя же пагинация должна быть везде, а не только в деве и тестах

2023-09-15 09:54 UTC, DariaAres commented on Gemfile
> +  gem 'kaminari'
переместила

2023-09-15 11:30 UTC, Iorhael approved these changes

2023-09-15 12:26 UTC, TsikhanauDzmitry approved these changes

2023-09-18 05:01 UTC, merged