Task: Add event model
DariaAres/trainee-planner pull request #28
Opened 2023-09-15 18:16 UTC by DariaAres

2023-09-23 06:30 UTC, Iorhael commented on app/models/event.rb
> +  validate :valid_date
Мне кажется, что лучше дать имя характеризующее конкретную валидацию, т.е. в данном случае что-то вроде `date_cannot_be_in_the_past`

2023-09-23 06:30 UTC, Iorhael commented on app/models/event.rb
> +  def date_present?
Мне кажется, что этот метод не нужен, можно просто писать `date_to_notificate.present?`, ну или сделать его приватным. Как считаешь?

2023-09-23 06:30 UTC, Iorhael commented on db/seeds/development.rb
> +    user: User.all.sample
Сделай, пожалуйста, чтобы события создавались только для пользователей и категорий, созданных в сидах.

2023-09-23 06:30 UTC, Iorhael commented on app/models/event.rb
> +  def valid_date_to_notificate
Если время напоминания, допустим, будет создано в прошедшем времени, но до события, то мы получим сообщение, что напоминание не может быть после самого события, что некорректно. Предлагаю сделать две валидации: для напоминаний в прошлом и напоминаний после события.

2023-09-23 06:30 UTC, Iorhael commented on spec/models/event_spec.rb
> +      it { expect(event).not_to be_valid }
Здесь и далее добавь, пожалуйста, проверки сообщений об ошибках.

2023-09-26 07:20 UTC, DariaAres commented on app/models/event.rb
> +    errors.add(:date, 'Date cannot be in the past')
добавила

2023-09-26 07:20 UTC, DariaAres commented on app/models/event.rb
> +    errors.add(:date_to_notificate, 'Mention of events cannot be later than their date')
добавила

2023-09-26 07:21 UTC, DariaAres commented on app/models/event.rb
> +  validate :valid_date
переименовала

2023-09-26 07:21 UTC, DariaAres commented on app/models/event.rb
> +  def date_present?
сделала приватным

2023-09-26 07:25 UTC, DariaAres commented on db/seeds/development.rb
> +    user: User.all.sample
сделала

2023-09-26 07:31 UTC, DariaAres commented on app/models/event.rb
> +  def valid_date_to_notificate
сделала

2023-09-26 11:29 UTC, DariaAres commented on spec/models/event_spec.rb
> +      it { expect(event).not_to be_valid }
добавила

2023-09-26 14:21 UTC, Iorhael submitted a review, later dismissed

2023-09-28 06:04 UTC, TsikhanauDzmitry requested changes

2023-09-28 06:04 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +  end
Эти все методы должны быть в `private` блоке

2023-09-28 06:04 UTC, TsikhanauDzmitry commented on app/models/event.rb
> +  end
Странный метод, честно говоря

2023-09-28 06:04 UTC, TsikhanauDzmitry commented on db/migrate/20230919072656_create_events.rb
> +      t.datetime :date, null: false
Не должно быть поля date для дат. Все поля должны максимально раскрывать смысл своей работы

2023-09-28 06:27 UTC, DariaAres commented on app/models/event.rb
> +  end
исправила

2023-09-28 06:58 UTC, DariaAres commented on app/models/event.rb
> +  end
Исправила

2023-09-28 06:58 UTC, DariaAres commented on db/migrate/20230919072656_create_events.rb
> +      t.datetime :date, null: false
Исправила

2023-09-28 12:01 UTC, TsikhanauDzmitry approved these changes

2023-09-29 12:50 UTC, Iorhael approved these changes

2023-09-29 16:42 UTC, merged