Task: Add event controller and view
DariaAres/trainee-planner pull request #29
Opened 2023-09-18 04:52 UTC by DariaAres

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/events_controller.rb
> +    @events = Event.all.page(params[:page]).per(20)
Здесь события выводятся для всех пользователей?

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/events_controller.rb
> +    @events = Event.all.page(params[:page]).per(20)
`per(20)` желательно вынести дефолтное значение в модель. Также следует добавить возможно изменения этого значения в параметрах запроса (`per_page`)

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/events_controller.rb
> +      redirect_to events_path
Здесь и далее можно в одну строчку.

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/events_controller.rb
> +      render :new, status: :unprocessable_entity
В одну строчку.

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/events_controller.rb
> +      redirect_to event_path(@event)
Можно в одну строчку.

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/events_controller.rb
> +      render :edit, status: :unprocessable_entity
Сделай, пожалуйста, в одну строчку.

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/events_controller.rb
> +  end
Добавь, пожалуйста, обработку случая проблем с удалением.

2023-10-06 08:49 UTC, Iorhael commented on app/controllers/home_controller.rb
> +require './app/services/user_events_service'
Хм, а без этой строчки не работает?

2023-10-06 08:56 UTC, Iorhael commented on app/helpers/events_helper.rb
Для чего этот файлик?

2023-10-10 08:16 UTC, DariaAres commented on app/controllers/events_controller.rb
> +    @events = Event.all.page(params[:page]).per(20)
исправила

2023-10-10 08:16 UTC, DariaAres commented on app/controllers/events_controller.rb
> +    @events = Event.all.page(params[:page]).per(20)
сделала

2023-10-10 08:16 UTC, DariaAres commented on app/controllers/events_controller.rb
> +      redirect_to events_path
сделала

2023-10-10 08:16 UTC, DariaAres commented on app/controllers/events_controller.rb
> +      render :new, status: :unprocessable_entity
сделала

2023-10-10 08:16 UTC, DariaAres commented on app/controllers/events_controller.rb
> +      redirect_to event_path(@event)
сделала

2023-10-10 08:16 UTC, DariaAres commented on app/controllers/events_controller.rb
> +      render :edit, status: :unprocessable_entity
сделала

2023-10-10 08:17 UTC, DariaAres commented on app/helpers/events_helper.rb
ни для чего) удалила

2023-10-10 08:19 UTC, DariaAres commented on app/controllers/home_controller.rb
> +require './app/services/user_events_service'
работатет))) Убрала

2023-10-11 11:43 UTC, Iorhael commented on app/controllers/events_controller.rb
> +    if @event.update(event_params)
А можем ли мы послать запрос на обновление события не у текущего пользователя (указать category_id, которой нет у текущего пользователя)?

2023-10-11 11:43 UTC, Iorhael commented on app/controllers/events_controller.rb
> +    if @event.destroy
А удалить событие, не принадлежащее текущему пользователю?

2023-10-11 11:43 UTC, Iorhael commented on app/controllers/home_controller.rb
Мне всё же кажется, что это немного не относится к данному PR-у. Как считаешь?

2023-10-11 11:43 UTC, Iorhael commented on app/views/events/_form.html.erb
> +                            { class: "form-control", placeholder: "Select category"} %>
Т.е. можно выбрать любую категорию? Даже если она не относится к пользователю?

2023-10-11 11:43 UTC, Iorhael commented on spec/features/events/create_spec.rb
Проверяй, пожалуйста, сообщения через `I18n`

2023-10-12 07:24 UTC, DariaAres commented on app/controllers/events_controller.rb
> +    if @event.update(event_params)
можем, исправила

2023-10-12 07:31 UTC, DariaAres commented on app/controllers/events_controller.rb
> +    if @event.destroy
Исправила. В метод find_event добавила поиск событий текущего пользователя => на страницу show чужего события пользователь не попадет => и удалить его не сможет так как delete можно выполить только через show страницу

2023-10-12 07:33 UTC, DariaAres commented on app/views/events/_form.html.erb
> +                            { class: "form-control", placeholder: "Select category"} %>
исправила

2023-10-13 15:02 UTC, DariaAres commented on spec/features/events/create_spec.rb
исправила

2023-10-13 15:03 UTC, DariaAres commented on app/controllers/events_controller.rb
> +    if @event.destroy
Можно, но если честно не вижу проблем

2023-10-16 09:41 UTC, DariaAres commented on app/controllers/home_controller.rb
создала отдельный ПР для них

2023-10-23 07:11 UTC, TsikhanauDzmitry requested changes

2023-10-23 07:11 UTC, TsikhanauDzmitry commented on app/controllers/events_controller.rb
> +    @events = current_user.events.all.page(params[:page]).per(params[:per_page]).order('event_date')
Аналогичное замечание: https://github.com/DariaAres/trainee-planner/pull/21#discussion_r1368209431

2023-10-23 07:11 UTC, TsikhanauDzmitry commented on app/views/events/index.html.erb
> +      <%else%>
Что-то с пробелами случилось

2023-10-23 07:11 UTC, TsikhanauDzmitry commented on app/views/events/index.html.erb
> +      <%= link_to "30", events_path(per_page: 30, search: params[:search]), class: "btn btn-secondary btn-short-width"%>
Давай это в отдельный `partial`

2023-10-24 05:53 UTC, DariaAres commented on app/views/events/index.html.erb
> +      <%else%>
исправила

2023-10-24 05:53 UTC, DariaAres commented on app/views/events/index.html.erb
> +      <%= link_to "30", events_path(per_page: 30, search: params[:search]), class: "btn btn-secondary btn-short-width"%>
исправила

2023-10-25 13:33 UTC, TsikhanauDzmitry approved these changes

2023-10-27 10:17 UTC, merged